### ISSUE TITLE
have you guys thought about IPython NoteBooks 

### ISSUE THREAD

**Issue by b-slim** [alegrand/RR_webinars#1]
It start to be a common used tools within the Data science community, i am not an expert but it looks like it is a potential tool to document your data manipulation interactively.

https://github.com/ipython/ipython/wiki/A-gallery-of-interesting-IPython-Notebooks.

**Comment by stanisic** [comment]
Indeed, IPython is a very nice tool, especially for the newcomers (students) and people already working with python. In the first webinar presentation, Arnaud Legrand briefly explained pros and cons of IPython and showed how to use it. 

In case you missed webinar presentation, the video will soon become available online. Until then you may want to check the slides https://github.com/alegrand/SMPE/raw/master/lectures/talk_16_03_07_Webinar.pdf
