### ISSUE TITLE
Broken link to the slides

### ISSUE THREAD

**Issue by ybayle** [alegrand/RR_webinars#12]
Hi,
The second link for the slides of 5_archiving_software_and_data is broken.
And the first link contains a corrupted pdf file.

**Comment by alegrand** [comment]
Thanks for noticing. The second link is indeed broken now and I've informed Roberto about this as he's the one maintaining it. This used to work as this is where I downloaded the slides in the first place. Regarding the first link, I just checked it out both with github preview and via a download on my machine and everything seems to work fine, hence closing.
